DROP TABLE MEMBER;
DROP SEQUENCE SEQ_MEMBER;

CREATE SEQUENCE SEQ_MEMBER NOCYCLE;

CREATE TABLE MEMBER (
	MEMBER_NO NUMBER PRIMARY KEY,
	MEMBER_ID VARCHAR2(100) UNIQUE NOT NULL,
	MEMBER_PWD VARCHAR2(100) NOT NULL,
	MEMBER_EMAIL VARCHAR2(120) UNIQUE NOT NULL,
	MEMBER_NAME VARCHAR2(100) UNIQUE NOT NULL,
	MEMBER_PHOTO_EXTEND	VARCHAR2(30),
	MEMBER_INFO	VARCHAR2(800),
	MEMBER_INSERT DATE DEFAULT SYSDATE	NOT NULL,
	MEMBER_DELETE DATE
);

INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_EMAIL, MEMBER_NAME) VALUES(SEQ_MEMBER.NEXTVAL, 'admin', '$2a$10$x30BjSzHW9D8hEjGewA.oOgTSBo0qFx/i.W4rIaOhkvUSNXoqHxsG', 'admin@coddy.com', '운영자');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_EMAIL, MEMBER_NAME) VALUES(SEQ_MEMBER.NEXTVAL, 'user01', '$2a$10$3tjfQjhaYjPtMf5GQC8qRez3qy2iKR0Z6AHwx3DhSdnc4uf1ZyBHC', 'user01@naver.com', '사용자01');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_EMAIL, MEMBER_NAME) VALUES(SEQ_MEMBER.NEXTVAL, 'user02', '$2a$10$CeHfaUCsK4.YK9261b2nn.WqK/SgNN9Z0PgvWveI7c8c4LpGdCvGW', 'user02@naver.com', '사용자02');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_EMAIL, MEMBER_NAME) VALUES(SEQ_MEMBER.NEXTVAL, 'user03', '$2a$10$h8gKprXaq6aHF4ryqz2.p.zg6LpKl2JCkO99ELOH0UsfqjDht4W6y', 'user03@naver.com', '사용자03');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_EMAIL, MEMBER_NAME) VALUES(SEQ_MEMBER.NEXTVAL, 'user04', '$2a$10$6Sv7r/TkS80tSeo1iH/y9ehY1EvJ1/Vvyawb.m1HmrZweFoF/L64O', 'user04@naver.com', '사용자04');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_EMAIL, MEMBER_NAME) VALUES(SEQ_MEMBER.NEXTVAL, 'user05', '$2a$10$ImZfEPLwMvb8mrUjFzqUxeePihnpZKWD5lcydH5/W0puXJ1veNxzC', 'user05@naver.com', '사용자05');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_EMAIL, MEMBER_NAME) VALUES(SEQ_MEMBER.NEXTVAL, 'user06', '$2a$10$BRgq1.9QK.idrJmRZQtjce9aOY2.Kj8m4xA8zdVcBOtXe0wih6SG2', 'user06@naver.com', '사용자06');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_EMAIL, MEMBER_NAME) VALUES(SEQ_MEMBER.NEXTVAL, 'user07', '$2a$10$YaeQ9UQIxZ5v971NMgtsL.bCq42doYajlajErtywGAK0hHIve9t9C', 'user07@naver.com', '사용자07');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_EMAIL, MEMBER_NAME) VALUES(SEQ_MEMBER.NEXTVAL, 'user08', '$2a$10$Aucw5mYVqvLqkcvvamJYA.ofjBn9IauzPUix5V3e4FBRyCl4BXZaK', 'user08@naver.com', '사용자08');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_EMAIL, MEMBER_NAME) VALUES(SEQ_MEMBER.NEXTVAL, 'user09', '$2a$10$CCFZG2eik3vIaoxWkMhK.eCctqYgC8e2vurGAdN7QFUOLe.TEdZui', 'user09@naver.com', '사용자09');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_EMAIL, MEMBER_NAME) VALUES(SEQ_MEMBER.NEXTVAL, 'user10', '$2a$10$m3xVzCzOucbLcBk3o.INxe4QHGYTl0P.q./wy.H5GeJpjlWRiXy8.', 'user10@naver.com', '사용자10');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_EMAIL, MEMBER_NAME) VALUES(SEQ_MEMBER.NEXTVAL, 'user11', '$2a$10$Qwjb36lA/SFAlKpc8z/.zuPGx2JFAk5CMQ4BcuO4jKGRrk1NvMZWu', 'user11@naver.com', '사용자11');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_EMAIL, MEMBER_NAME) VALUES(SEQ_MEMBER.NEXTVAL, 'user12', '$2a$10$ZQGPfZoZY519KvFzxEIho.7zGyp3HxMVmwuR9fqqPkgR9QKgbxG2K', 'user12@naver.com', '사용자12');

COMMIT;