DROP TABLE CHAT;
DROP SEQUENCE SEQ_CHAT;

CREATE SEQUENCE SEQ_CHAT NOCYCLE;

CREATE TABLE CHAT (
	CHAT_NO	NUMBER	PRIMARY KEY,
	CHAT_MEMBER1	NUMBER		NULL,
	CHAT_MEMBER2	NUMBER		NULL,
	PROJECT_NO	NUMBER		NULL,
    FOREIGN KEY (CHAT_MEMBER1) REFERENCES MEMBER(MEMBER_NO),
    FOREIGN KEY (CHAT_MEMBER2) REFERENCES MEMBER(MEMBER_NO),
    FOREIGN KEY (PROJECT_NO) REFERENCES PROJECT(PROJECT_NO)
);

DROP TABLE CHAT_RECORD;
DROP SEQUENCE SEQ_CHAT_RECORD;

CREATE SEQUENCE SEQ_CHAT_RECORD NOCYCLE;

CREATE TABLE CHAT_RECORD (
	CHATR_NO NUMBER PRIMARY KEY,
	CHAT_NO	NUMBER		NOT NULL,
	CHATR_SENDER	NUMBER		NOT NULL,
	CHATR_MSG	VARCHAR2(2000)		NOT NULL,
	CHATR_INSERT	DATE	DEFAULT SYSDATE	NOT NULL,
	CHATR_UPDATE	DATE		NULL,
	CHATR_DELETE	DATE		NULL,
    FOREIGN KEY (CHAT_NO) REFERENCES CHAT(CHAT_NO),
    FOREIGN KEY (CHATR_SENDER) REFERENCES MEMBER(MEMBER_NO)
);

COMMIT;