DROP TABLE CHAT;


CREATE TABLE CHAT (
	PROJECT_NO NUMBER NOT NULL,
	CHAT_MASTER NUMBER NOT NULL,
	CHAT_INSERT DATE DEFAULT SYSDATE NOT NULL
	FOREIGN KEY (CHAT_MASTER) REFERENCES MEMBER(MEMBER_NO),
	FOREIGN KEY (PROJECT_NO) REFERENCES PROJECT(PROJECT_NO)
);

DROP TABLE CHAT_RECORD;
DROP SEQUENCE SEQ_CHAT_RECORD;

CREATE SEQUENCE SEQ_CHAT_RECORD NOCYCLE;

CREATE TABLE CHAT_RECORD (
	CHATR_NO	NUMBER 		PRIMARY KEY,
	PROJECT_NO 	NUMBER		NOT NULL,
	CHATR_SENDER	NUMBER		NOT NULL,
	CHATR_MSG	VARCHAR2(2000)		NOT NULL,
	CHATR_TYPE	NUMBER		NOT NULL,
	CHATR_INSERT	DATE	DEFAULT SYSDATE	NOT NULL,
	CHATR_UPDATE	DATE		NULL,
	CHATR_DELETE	DATE		NULL,
    FOREIGN KEY (CHATR_SENDER) REFERENCES MEMBER(MEMBER_NO),
    FOREIGN KEY (PROJECT_NO) REFERENCES PROJECT(PROJECT_NO)
);

COMMIT;

DROP TABLE CHAT_MEMBER;

CREATE TABLE CHAT_MEMBER(
	PROJECT_NO	NUMBER	NOT NULL,
	MEMBER_NO	NUMBER	NOT NULL,
	ROLE		VARCHAR2(60) NOT NULL,
	FOREIGN KEY (PROJECT_NO) REFERENCES PROJECT(PROJECT_NO),
    	FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO)
);

COMMIT;