DROP TABLE CALENDAR;
DROP SEQUENCE SEQ_CALENDAR;

CREATE SEQUENCE SEQ_CALENDAR NOCYCLE;

CREATE TABLE CALENDAR (
	CALENDAR_NO	NUMBER	PRIMARY KEY,
	PROJECT_NO	NUMBER		NOT NULL,
	CALENDAR_TITLE	VARCHAR2(200)		NOT NULL,
	START_POINT	DATE		NOT NULL,
	END_POINT	DATE		NOT NULL,
    FOREIGN KEY (PROJECT_NO) REFERENCES PROJECT(PROJECT_NO)
);

COMMIT;