DROP SEQUENCE SEQ_RECRUITMENT_STATE;

CREATE SEQUENCE SEQ_RECRUITMENT_STATE NOCYCLE;

CREATE TABLE RECRUITMENT_STATE (
    RECRUITEMNT_STATE_NO   NUMBER      PRIMARY KEY,
	RECRUITMENT_NO		NUMBER		NOT NULL,
	ROLE			VARCHAR2(60)	NOT NULL,
	MAX_PERSONNEL		NUMBER		DEFAULT 1 	NOT NULL,
	FOREIGN KEY (RECRUITMENT_NO) REFERENCES RECRUITMENT (RECRUITMENT_NO)
);

COMMIT;
DROP TABLE APPLY_PERSONNEL;
CREATE TABLE APPLY_PERSONNEL(
    RECRUITMENT_STATE_NO    NUMBER NOT NULL,
    MEMBER_NO   NUMBER  NOT NULL,
    FOREIGN KEY (RECRUITMENT_STATE_NO) REFERENCES RECRUITMENT_STATE (RECRUITMENT_STATE_NO),
    FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO)
);

COMMIT;
