DROP TABLE RECRUITMENT_STATE;

CREATE TABLE RECRUITMENT_STATE (
	PROJECT_NO	NUMBER		NOT NULL,
	JOINS_NO	NUMBER		NOT NULL,
	ROLE	VARCHAR2(60)		NOT NULL,
	PERSONNEL	NUMBER	DEFAULT 1	NOT NULL CHECK(PERSONNEL > 0),
    FOREIGN KEY (PROJECT_NO) REFERENCES PROJECT(PROJECT_NO),
    FOREIGN KEY (JOINS_NO) REFERENCES JOINS(JOINS_NO)
);

COMMIT;