// only drop
DROP TABLE RECRUITMENT_STATE;
DROP TABLE CALENDAR;
DROP TABLE HRELATION;
DROP TABLE HATTACHMENT;
DROP TABLE HWISHLIST;
DROP TABLE HBOARD;
DROP TABLE CRELATION;
DROP TABLE RECOMMEND;
DROP TABLE RCATTACHMENT;
DROP TABLE CREPLY;
DROP TABLE CATTACHMENT;
DROP TABLE CBOARD;
DROP TABLE IATTACHMENT;
DROP TABLE IREPLY;
DROP TABLE LIKES;
DROP TABLE IBOARD;
DROP TABLE NATTACHMENT;
DROP TABLE NBOARD;
DROP TABLE FATTACHMENT;
DROP TABLE FREPLY;
DROP TABLE FBOARD;
DROP TABLE PRELATION;
DROP TABLE MRELATION;
DROP TABLE TAGS;
DROP TABLE COMPANY;
DROP TABLE CHAT_RECORD;
DROP TABLE CHAT;
DROP TABLE REVIEW;
DROP TABLE JOINS;
DROP TABLE PROJECT;
DROP TABLE RECRUITMENT_ATTACHMENT;
DROP TABLE RECRUITMENT_REPLY;
DROP TABLE RECRUITMENT_WISHLIST;
DROP TABLE AUTH;
DROP TABLE RECRUITMENT;
DROP TABLE MEMBER;
DROP TABLE RECRUITMENT_STATE;
DROP TABLE APPLY_PERSONNEL;



DROP SEQUENCE SEQ_MEMBER;

CREATE SEQUENCE SEQ_MEMBER NOCYCLE;

CREATE TABLE MEMBER (
	MEMBER_NO NUMBER PRIMARY KEY,
	MEMBER_ID VARCHAR2(100) UNIQUE NOT NULL,
	MEMBER_PWD VARCHAR2(100) NOT NULL,
	MEMBER_EMAIL VARCHAR2(120) UNIQUE NOT NULL,
	MEMBER_NAME VARCHAR2(100) UNIQUE NOT NULL,
	MEMBER_PHOTO_EXTEND	VARCHAR2(30),
	MEMBER_INFO	VARCHAR2(800),
	MEMBER_INSERT DATE DEFAULT SYSDATE	NOT NULL,
	MEMBER_DELETE DATE
);

INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_EMAIL, MEMBER_NAME) VALUES(SEQ_MEMBER.NEXTVAL, 'admin', '$2a$10$x30BjSzHW9D8hEjGewA.oOgTSBo0qFx/i.W4rIaOhkvUSNXoqHxsG', 'admin@coddy.com', '운영자');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_EMAIL, MEMBER_NAME) VALUES(SEQ_MEMBER.NEXTVAL, 'user01', '$2a$10$3tjfQjhaYjPtMf5GQC8qRez3qy2iKR0Z6AHwx3DhSdnc4uf1ZyBHC', 'user01@naver.com', '사용자01');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PWD, MEMBER_EMAIL, MEMBER_NAME) VALUES(SEQ_MEMBER.NEXTVAL, 'user02', '$2a$10$CeHfaUCsK4.YK9261b2nn.WqK/SgNN9Z0PgvWveI7c8c4LpGdCvGW', 'user02@naver.com', '사용자02');

COMMIT;

CREATE TABLE AUTH (
	AUTH_INSERT	DATE DEFAULT SYSDATE NOT NULL,
	AUTH_VALUE VARCHAR2(80) NOT NULL,
	AUTH_EMAIl VARCHAR2(120) NOT NULL
);

COMMIT;

-- 인엽씨
DROP SEQUENCE SEQ_RECRUITMENT;

CREATE SEQUENCE SEQ_RECRUITMENT NOCYCLE;

CREATE TABLE RECRUITMENT (
	RECRUITMENT_NO	NUMBER PRIMARY KEY,
	RECRUITMENT_TITLE	VARCHAR2(400)		NOT NULL,
	RECRUITMENT_CONTENT	VARCHAR2(4000)		NOT NULL,
	RECRUITMENT_WRITER	NUMBER		NULL,
	RECRUITMENT_INSERT	DATE	DEFAULT SYSDATE	NOT NULL,
	RECRUITMENT_UPDATE	DATE		NULL,
	RECRUITMENT_DELETE	DATE		NULL,
	RECRUITMENT_VIEWS	NUMBER	DEFAULT 0	NOT NULL,
	RECRUITMENT_START	DATE		NULL,
	RECRUITMENT_END	DATE		NULL,
	RECRUITMENT_LOCATION	VARCHAR2(200)		NULL,
    RECRUITMENT_INTRO VARCHAR2(500)   NOT NULL,
    FOREIGN KEY (RECRUITMENT_WRITER) REFERENCES MEMBER(MEMBER_NO)
);

COMMENT ON COLUMN RECRUITMENT.RECRUITMENT_INSERT IS '작성된 날짜';

CREATE TABLE RECRUITMENT_WISHLIST (
	RECRUITMENT_WISHLIST_MEMBER	NUMBER		NOT NULL,
	RECRUITMENT_NO	NUMBER		NOT NULL,
    FOREIGN KEY (RECRUITMENT_WISHLIST_MEMBER) REFERENCES MEMBER(MEMBER_NO),
    FOREIGN KEY (RECRUITMENT_NO) REFERENCES RECRUITMENT(RECRUITMENT_NO)
);

DROP SEQUENCE SEQ_RECRUITMENT_REPLY;

CREATE SEQUENCE SEQ_RECRUITMENT_REPLY NOCYCLE;

CREATE TABLE RECRUITMENT_REPLY (
	RECRUITMENT_REPLY_NO	NUMBER PRIMARY KEY,
	MEMBER_NO	NUMBER		NOT NULL,
	RECRUITMENT_NO	NUMBER		NOT NULL,
	RECRUITMENT_REPLY_PARENT	NUMBER		NOT NULL,
	RECRUITMENT_REPLY_CONTENT	VARCHAR2(2000)		NOT NULL,
	RECRUITMENT_REPLY_INSERT	DATE	DEFAULT SYSDATE	NOT NULL,
	RECRUITMENT_REPLY_UPDATE	DATE		NULL,
	RECRUITMENT_REPLY_DELETE	DATE		NULL,
    FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO),
    FOREIGN KEY (RECRUITMENT_NO) REFERENCES RECRUITMENT(RECRUITMENT_NO),
    FOREIGN KEY (RECRUITMENT_REPLY_PARENT) REFERENCES RECRUITMENT_REPLY(RECRUITMENT_REPLY_NO)
);

DROP SEQUENCE SEQ_RECRUITMENT_ATTACHMENT;

CREATE SEQUENCE SEQ_RECRUITMENT_ATTACHMENT NOCYCLE;

CREATE TABLE RECRUITMENT_ATTACHMENT (
	RECRUITMENT_ATTACHMENT_NO	NUMBER PRIMARY KEY,
	RECRUITMENT_NO	NUMBER		NOT NULL,
	RECRUITMENT_ATTACHMENT_ORIGIN	VARCHAR2(200)		NOT NULL,
	RECRUITMENT_ATTACHMENT_CHANGE	VARCHAR2(200)		NOT NULL,
	RECRUITMENT_ATTACHMENT_PATH	VARCHAR2(200)		NOT NULL,
	RECRUITMENT_ATTACHMENT_INSERT	DATE	DEFAULT SYSDATE	NOT NULL,
	RECRUITMENT_ATTACHMENT_LEVEL	NUMBER	DEFAULT 0	NOT NULL,
    FOREIGN KEY (RECRUITMENT_NO) REFERENCES RECRUITMENT(RECRUITMENT_NO)
);

COMMIT;

DROP SEQUENCE SEQ_PROJECT;

CREATE SEQUENCE SEQ_PROJECT NOCYCLE;

CREATE TABLE PROJECT (
	PROJECT_NO NUMBER PRIMARY KEY,
	PROJECT_OWNER NUMBER NOT NULL,
    RECRUITMENT_NO NUMBER NOT NULL,
	PROJECT_NAME VARCHAR2(400) NOT NULL,
	PROJECT_INFO VARCHAR2(4000) NULL,
	PROJECT_INSERT DATE	DEFAULT SYSDATE	NOT NULL,
	PROJECT_START DATE NOT NULL,
	PROJECT_END	DATE NOT NULL,
	PROJECT_LOCATION VARCHAR2(200) NULL,
	PROJECT_READY NUMBER DEFAULT 0 NOT NULL,
    FOREIGN KEY (RECRUITMENT_NO) REFERENCES RECRUITMENT(RECRUITMENT_NO),
    FOREIGN KEY (PROJECT_OWNER) REFERENCES MEMBER(MEMBER_NO)
);

COMMIT;

DROP SEQUENCE SEQ_JOINS;

CREATE SEQUENCE SEQ_JOINS NOCYCLE;

CREATE TABLE JOINS (
	JOINS_NO NUMBER PRIMARY KEY,
	MEMBER_NO NUMBER NOT NULL,
	PROJECT_NO NUMBER NOT NULL,
	JOINS_ROLE VARCHAR2(60) NULL,
	JOINS_IS_PUBLIC	NUMBER DEFAULT 0 NOT NULL,
	JOINS_ACTIVATE NUMBER DEFAULT 1	NOT NULL,
	JOINS_REVIEW VARCHAR2(2000) NULL,
    FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO),
    FOREIGN KEY (PROJECT_NO) REFERENCES PROJECT(PROJECT_NO)
);

COMMENT ON COLUMN JOINS.JOINS_IS_PUBLIC IS '0=PRIVATE, 1=PUBLIC';
COMMENT ON COLUMN JOINS.JOINS_ACTIVATE IS '0: 강제퇴장 / 1: 정상 / 2: 본인퇴장 / 3: 대기실폭발';

COMMIT;

CREATE TABLE REVIEW (
	REVIEW_PROJECT	NUMBER		NOT NULL,
	REVIEW_SUBJECT	NUMBER		NOT NULL,
	REVIEW_OBJECT	NUMBER		NOT NULL,
	REVIEW_SCORE	NUMBER	DEFAULT 1.0 CHECK(REVIEW_SCORE <= 5.0 AND REVIEW_SCORE >= 1.0) NOT NULL,
	REVIEW_REASON	VARCHAR2(800)		NULL,
    FOREIGN KEY (REVIEW_PROJECT) REFERENCES PROJECT(PROJECT_NO),
    FOREIGN KEY (REVIEW_SUBJECT) REFERENCES MEMBER(MEMBER_NO),
    FOREIGN KEY (REVIEW_OBJECT) REFERENCES MEMBER(MEMBER_NO)
);

COMMIT;

DROP SEQUENCE SEQ_CHAT;

CREATE SEQUENCE SEQ_CHAT NOCYCLE;

CREATE TABLE CHAT (
	CHAT_MEMBER1	NUMBER		NULL,
	CHAT_MEMBER2	NUMBER		NULL,
	PROJECT_NO	NUMBER		NULL,
    FOREIGN KEY (CHAT_MEMBER1) REFERENCES MEMBER(MEMBER_NO),
    FOREIGN KEY (CHAT_MEMBER2) REFERENCES MEMBER(MEMBER_NO),
    FOREIGN KEY (PROJECT_NO) REFERENCES PROJECT(PROJECT_NO)
);

DROP SEQUENCE SEQ_CHAT_RECORD;

CREATE SEQUENCE SEQ_CHAT_RECORD NOCYCLE;

CREATE TABLE CHAT_RECORD (
	CHATR_NO NUMBER PRIMARY KEY,
	CHATR_SENDER	NUMBER		NOT NULL,
    PROJECT_NO NUMBER,
	CHATR_MSG	VARCHAR2(2000)		NOT NULL,
	CHATR_INSERT	DATE	DEFAULT SYSDATE	NOT NULL,
	CHATR_UPDATE	DATE		NULL,
	CHATR_DELETE	DATE		NULL,
    FOREIGN KEY (CHATR_SENDER) REFERENCES MEMBER(MEMBER_NO),
    FOREIGN KEY (PROJECT_NO) REFERENCES PROJECT(PROJECT_NO)
);

COMMIT;

DROP SEQUENCE SEQ_COMPANY;

CREATE SEQUENCE SEQ_COMPANY NOCYCLE;

CREATE TABLE COMPANY (
	COMPANY_NO	NUMBER	PRIMARY KEY,
	COMPANY_NAME	VARCHAR2(100)		NOT NULL,
	COMPANY_OWNER	VARCHAR2(40)		NOT NULL,
	COMPANY_ID	VARCHAR2(100)		NOT NULL UNIQUE,
	COMPANY_PWD	VARCHAR2(100)		NOT NULL,
	COMPANY_EMAIL	VARCHAR2(120)		NOT NULL UNIQUE,
	COMPANY_PHOTO_EXTEND	VARCHAR2(30)		NULL,
	COMPANY_BNO	VARCHAR2(300)		NOT NULL UNIQUE,
	COMPANY_INFO	VARCHAR2(2000)		NULL,
	COMPANY_INSERT	DATE	DEFAULT SYSDATE	NOT NULL,
	COMPANY_DELETE	DATE		NULL,
	COMPANY_WORKER	NUMBER	DEFAULT 1	NOT NULL,
	COMPANY_SALARY	NUMBER	DEFAULT 0	NOT NULL
);

INSERT INTO COMPANY(COMPANY_NO, COMPANY_ID, COMPANY_PWD, COMPANY_EMAIL, COMPANY_NAME, COMPANY_OWNER, COMPANY_BNO, COMPANY_INFO, COMPANY_WORKER, COMPANY_SALARY) VALUES(SEQ_COMPANY.NEXTVAL, 'company', '$2a$10$J1rPzY5.J8mb8DhHjnv4t.ncEytRQ2Y5ejOCU2Tdcrtv3mI30YR5q', 'company@coddy.com', 'company', '김인엽', 8164700297, 'company계정', 23, 46000000);

COMMIT;

DROP SEQUENCE SEQ_TAGS;

CREATE SEQUENCE SEQ_TAGS NOCYCLE;

CREATE TABLE TAGS (
	TAGS_NO	NUMBER PRIMARY KEY,
	TAGS_NAME	VARCHAR2(200)		NOT NULL,
	TAGS_TYPE	NUMBER CHECK(TAGS_TYPE IN(0, 1))	NOT NULL,
	TAGS_ACTIVE	NUMBER DEFAULT 1 CHECK(TAGS_ACTIVE IN(0, 1))	NOT NULL
);

COMMENT ON COLUMN TAGS.TAGS_TYPE IS '0: 기술태그 / 1:직군태그';
COMMENT ON COLUMN TAGS.TAGS_ACTIVE IS '0:비활성';

INSERT INTO TAGS VALUES(SEQ_TAGS.NEXTVAL, 'C언어', 0, 1);
INSERT INTO TAGS VALUES(SEQ_TAGS.NEXTVAL, 'C++', 0, 1);
INSERT INTO TAGS VALUES(SEQ_TAGS.NEXTVAL, 'C#', 0, 1);
INSERT INTO TAGS VALUES(SEQ_TAGS.NEXTVAL, 'GO', 0, 1);
INSERT INTO TAGS VALUES(SEQ_TAGS.NEXTVAL, 'Java', 0, 1);
INSERT INTO TAGS VALUES(SEQ_TAGS.NEXTVAL, 'JavaScript', 0, 1);
INSERT INTO TAGS VALUES(SEQ_TAGS.NEXTVAL, 'Spring', 0, 1);
INSERT INTO TAGS VALUES(SEQ_TAGS.NEXTVAL, 'React', 0, 1);
INSERT INTO TAGS VALUES(SEQ_TAGS.NEXTVAL, 'Node.js', 0, 1);
INSERT INTO TAGS VALUES(SEQ_TAGS.NEXTVAL, 'Vue', 0, 1);
INSERT INTO TAGS VALUES(SEQ_TAGS.NEXTVAL, 'Swift', 0, 1);
INSERT INTO TAGS VALUES(SEQ_TAGS.NEXTVAL, 'Kotlin', 0, 1);
INSERT INTO TAGS VALUES(SEQ_TAGS.NEXTVAL, 'Python', 0, 1);
INSERT INTO TAGS VALUES(SEQ_TAGS.NEXTVAL, 'Django', 0, 1);
INSERT INTO TAGS VALUES(SEQ_TAGS.NEXTVAL, 'Php', 0, 1);
INSERT INTO TAGS VALUES(SEQ_TAGS.NEXTVAL, 'Flutter', 0, 1);

INSERT INTO TAGS VALUES(SEQ_TAGS.NEXTVAL, 'MySql', 0, 1);
INSERT INTO TAGS VALUES(SEQ_TAGS.NEXTVAL, 'MarianDB', 0, 1);
INSERT INTO TAGS VALUES(SEQ_TAGS.NEXTVAL, 'MongoDB', 0, 1);
INSERT INTO TAGS VALUES(SEQ_TAGS.NEXTVAL, 'OracleDB', 0, 1);

INSERT INTO TAGS VALUES(SEQ_TAGS.NEXTVAL, 'Unity', 0, 1);

INSERT INTO TAGS VALUES(SEQ_TAGS.NEXTVAL, 'AWS', 0, 1);
INSERT INTO TAGS VALUES(SEQ_TAGS.NEXTVAL, 'Docker', 0, 1);
INSERT INTO TAGS VALUES(SEQ_TAGS.NEXTVAL, 'Kubernetes', 0, 1);
INSERT INTO TAGS VALUES(SEQ_TAGS.NEXTVAL, 'Git', 0, 1);
INSERT INTO TAGS VALUES(SEQ_TAGS.NEXTVAL, 'Figma', 0, 1);

INSERT INTO TAGS VALUES(SEQ_TAGS.NEXTVAL, 'Window', 0, 1);
INSERT INTO TAGS VALUES(SEQ_TAGS.NEXTVAL, 'Linux', 0, 1);

INSERT INTO TAGS VALUES(SEQ_TAGS.NEXTVAL, 'PM', 1, 1);
INSERT INTO TAGS VALUES(SEQ_TAGS.NEXTVAL, '기획', 1, 1);
INSERT INTO TAGS VALUES(SEQ_TAGS.NEXTVAL, '프론트엔드', 1, 1);
INSERT INTO TAGS VALUES(SEQ_TAGS.NEXTVAL, '백엔드', 1, 1);
INSERT INTO TAGS VALUES(SEQ_TAGS.NEXTVAL, 'CDN', 1, 1);
INSERT INTO TAGS VALUES(SEQ_TAGS.NEXTVAL, '디자인', 1, 1);
INSERT INTO TAGS VALUES(SEQ_TAGS.NEXTVAL, '네트워크/서버', 1, 1);
INSERT INTO TAGS VALUES(SEQ_TAGS.NEXTVAL, 'IOS 앱 개발', 1, 1);
INSERT INTO TAGS VALUES(SEQ_TAGS.NEXTVAL, 'AOS 앱 개발', 1, 1);
INSERT INTO TAGS VALUES(SEQ_TAGS.NEXTVAL, 'AI학습', 1, 1);
INSERT INTO TAGS VALUES(SEQ_TAGS.NEXTVAL, '게임개발', 1, 1);

COMMIT;

CREATE TABLE MRELATION (
	MEMBER_NO	NUMBER		NOT NULL,
	TAGS_NO	NUMBER		NOT NULL,
    FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO),
    FOREIGN KEY (TAGS_NO) REFERENCES TAGS(TAGS_NO)
);

CREATE TABLE PRELATION (
	RECRUITMENT_NO	NUMBER		NOT NULL,
	TAGS_NO	NUMBER		NOT NULL,
    FOREIGN KEY (RECRUITMENT_NO) REFERENCES RECRUITMENT(RECRUITMENT_NO),
    FOREIGN KEY (TAGS_NO) REFERENCES TAGS(TAGS_NO)
);

COMMIT;

-- 효중씨
DROP SEQUENCE SEQ_FBOARD;

CREATE SEQUENCE SEQ_FBOARD NOCYCLE;

CREATE TABLE FBOARD (
	FBOARD_NO	NUMBER PRIMARY KEY,
	FBOARD_TITLE	VARCHAR2(400)		NOT NULL,
	FBOARD_CONTENT	VARCHAR2(4000)		NOT NULL,
	FBOARD_WRITER	NUMBER		NULL,
	FBOARD_INSERT	DATE	DEFAULT SYSDATE	NOT NULL,
	FBOARD_UPDATE	DATE		NULL,
	FBOARD_DELETE	DATE		NULL,
	FBOARD_VIEWS	NUMBER	DEFAULT 0	NOT NULL,
    FOREIGN KEY (FBOARD_WRITER) REFERENCES MEMBER(MEMBER_NO)
);

COMMENT ON COLUMN FBOARD.FBOARD_INSERT IS '작성된 날짜';

DROP SEQUENCE SEQ_FREPLY;

CREATE SEQUENCE SEQ_FREPLY NOCYCLE;

CREATE TABLE FREPLY (
	FREPLY_NO	NUMBER	PRIMARY KEY,
	MEMBER_NO	NUMBER		NOT NULL,
	FBOARD_NO	NUMBER		NOT NULL,
	FREPLY_PARENT	NUMBER		NULL,
	FREPLY_CONTENT	VARCHAR2(2000)		NOT NULL,
	FREPLY_INSERT	DATE	DEFAULT SYSDATE	NOT NULL,
	FREPLY_UPDATE	DATE		NULL,
	FREPLY_DELETE	DATE		NULL,
    FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO),
    FOREIGN KEY (FBOARD_NO) REFERENCES FBOARD(FBOARD_NO),
    FOREIGN KEY (FREPLY_PARENT) REFERENCES FREPLY(FREPLY_NO)
);

DROP SEQUENCE SEQ_FATTACHMENT;

CREATE SEQUENCE SEQ_FATTACHMENT NOCYCLE;

CREATE TABLE FATTACHMENT (
	FATTACHMENT_NO	NUMBER PRIMARY KEY,
	FBOARD_NO	NUMBER		NOT NULL,
	FATTACHMENT_ORIGIN	VARCHAR2(200)		NOT NULL,
	FATTACHMENT_CHANGE	VARCHAR2(200)		NOT NULL,
	FATTACHMENT_PATH	VARCHAR2(200)		NOT NULL,
	FATTACHMENT_INSERT	DATE	DEFAULT SYSDATE	NOT NULL,
	FATTACHMENT_LEVEL	NUMBER	DEFAULT 0	NOT NULL,
    FOREIGN KEY (FBOARD_NO) REFERENCES FBOARD(FBOARD_NO)
);

DROP SEQUENCE SEQ_NBOARD;

CREATE SEQUENCE SEQ_NBOARD NOCYCLE;

CREATE TABLE NBOARD (
	NBOARD_NO	NUMBER PRIMARY KEY,
	NBOARD_TITLE	VARCHAR2(400)		NOT NULL,
	NBOARD_CONTENT	VARCHAR2(4000)		NOT NULL,
	NBOARD_INSERT	DATE	DEFAULT SYSDATE	NOT NULL,
	NBOARD_UPDATE	DATE		NULL,
	NBOARD_DELETE	DATE		NULL,
	NBOARD_VIEWS	NUMBER	DEFAULT 0	NOT NULL
);

COMMENT ON COLUMN NBOARD.NBOARD_INSERT IS '작성된 날짜';

DROP SEQUENCE SEQ_NATTACHMENT;

CREATE SEQUENCE SEQ_NATTACHMENT NOCYCLE;

CREATE TABLE NATTACHMENT (
	NATTACHMENT_NO	NUMBER PRIMARY KEY,
	NBOARD_NO	NUMBER		NOT NULL,
	NATTACHMENT_ORIGIN	VARCHAR2(200)		NOT NULL,
	NATTACHMENT_CHANGE	VARCHAR2(200)		NOT NULL,
	NATTACHMENT_PATH	VARCHAR2(200)		NOT NULL,
	NATTACHMENT_INSERT	DATE	DEFAULT SYSDATE	NOT NULL,
	NATTACHMENT_LEVEL	NUMBER	DEFAULT 0	NOT NULL,
    FOREIGN KEY (NBOARD_NO) REFERENCES NBOARD(NBOARD_NO)
);

-- 영욱씨
DROP SEQUENCE SEQ_IBOARD;

CREATE SEQUENCE SEQ_IBOARD NOCYCLE;

CREATE TABLE IBOARD (
	IBOARD_NO	NUMBER PRIMARY KEY,
	IBOARD_TITLE	VARCHAR2(400)		NOT NULL,
	IBOARD_CONTENT	VARCHAR2(4000)		NOT NULL,
	IBOARD_WRITER	NUMBER		NULL,
	IBOARD_INSERT	DATE	DEFAULT SYSDATE	NOT NULL,
	IBOARD_UPDATE DATE		NULL,
	IBOARD_DELETE	DATE		NULL,
	PROJECT_NO	NUMBER		NOT NULL,
	IBOARD_VIEWS	NUMBER	DEFAULT 0	NOT NULL,
    FOREIGN KEY (IBOARD_WRITER) REFERENCES MEMBER(MEMBER_NO),
    FOREIGN KEY (PROJECT_NO) REFERENCES PROJECT(PROJECT_NO)
);

COMMENT ON COLUMN IBOARD.IBOARD_INSERT IS '작성된 날짜';

CREATE TABLE LIKES (
	LIKES_MEMBER	NUMBER		NOT NULL,
	IBOARD_NO	NUMBER		NOT NULL,
    FOREIGN KEY (LIKES_MEMBER) REFERENCES MEMBER(MEMBER_NO),
    FOREIGN KEY (IBOARD_NO) REFERENCES IBOARD(IBOARD_NO)
);

DROP SEQUENCE SEQ_IREPLY;

CREATE SEQUENCE SEQ_IREPLY NOCYCLE;

CREATE TABLE IREPLY (
	IREPLY_NO	NUMBER PRIMARY KEY,
	MEMBER_NO	NUMBER		NOT NULL,
	IBOARD_NO	NUMBER		NOT NULL,
	IREPLY_PARENT	NUMBER		NULL,
	IREPLY_CONTENT	VARCHAR2(2000)		NOT NULL,
	IREPLY_INSERT	DATE	DEFAULT SYSDATE	NOT NULL,
	IREPLY_UPDATE	DATE		NULL,
	IREPLY_DELETE	DATE		NULL,
    FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO),
    FOREIGN KEY (IBOARD_NO) REFERENCES IBOARD(IBOARD_NO),
    FOREIGN KEY (IREPLY_PARENT) REFERENCES IREPLY(IREPLY_NO)
);

DROP SEQUENCE SEQ_IATTACHMENT;

CREATE SEQUENCE SEQ_IATTACHMENT NOCYCLE;

CREATE TABLE IATTACHMENT (
	IATTACHMENT_NO	NUMBER PRIMARY KEY,
	IBOARD_NO	NUMBER		NOT NULL,
	IATTACHMENT_ORIGIN	VARCHAR2(200)		NOT NULL,
	IATTACHMENT_CHANGE	VARCHAR2(200)		NOT NULL,
	IATTACHMENT_PATH	VARCHAR2(200)		NOT NULL,
	IATTACHMENT_INSERT	DATE	DEFAULT SYSDATE	NOT NULL,
	IATTACHMENT_LEVEL	NUMBER	DEFAULT 0	NOT NULL,
    FOREIGN KEY (IBOARD_NO) REFERENCES IBOARD(IBOARD_NO)
);

-- 은지씨
DROP SEQUENCE SEQ_CBOARD;

CREATE SEQUENCE SEQ_CBOARD NOCYCLE;

CREATE TABLE CBOARD (
	CBOARD_NO	NUMBER PRIMARY KEY,
	CBOARD_TITLE	VARCHAR2(400)		NOT NULL,
	CBOARD_CONTENT	VARCHAR2(4000)		NOT NULL,
	CBOARD_WRITER	NUMBER		NULL,
	CBOARD_INSERT	DATE	DEFAULT SYSDATE	NOT NULL,
	CBOARD_UPDATE	DATE		NULL,
	CBOARD_DELETE	DATE		NULL,
	CBOARD_VIEWS	NUMBER	DEFAULT 0	NOT NULL,
    FOREIGN KEY (CBOARD_WRITER) REFERENCES MEMBER(MEMBER_NO)
);

COMMENT ON COLUMN CBOARD.CBOARD_TITLE IS '글제목';
COMMENT ON COLUMN CBOARD.CBOARD_CONTENT IS '글내용';
COMMENT ON COLUMN CBOARD.CBOARD_WRITER IS '저자';
COMMENT ON COLUMN CBOARD.CBOARD_INSERT IS '작성된 날짜';
COMMENT ON COLUMN CBOARD.CBOARD_UPDATE IS '글작성';
COMMENT ON COLUMN CBOARD.CBOARD_DELETE IS '글삭제';
COMMENT ON COLUMN CBOARD.CBOARD_VIEWS IS '조회수';

DROP SEQUENCE SEQ_CATTACHMENT;

CREATE SEQUENCE SEQ_CATTACHMENT NOCYCLE;

CREATE TABLE CATTACHMENT (
	CATTACHMENT_NO	NUMBER PRIMARY KEY,
	CBOARD_NO	NUMBER		NOT NULL,
	CATTACHMENT_ORIGIN	VARCHAR2(200)		NOT NULL,
	CATTACHMENT_CHANGE	VARCHAR2(200)		NOT NULL,
	CATTACHMENT_PATH	VARCHAR2(200)		NOT NULL,
	CATTACHMENT_INSERT	DATE	DEFAULT SYSDATE	NOT NULL,
	CATTACHMENT_LEVEL	NUMBER	DEFAULT 0	NOT NULL,
    FOREIGN KEY (CBOARD_NO) REFERENCES CBOARD(CBOARD_NO)
);

DROP SEQUENCE SEQ_CREPLY;

CREATE SEQUENCE SEQ_CREPLY NOCYCLE;

CREATE TABLE CREPLY (
	CREPLY_NO	NUMBER PRIMARY KEY,
	MEMBER_NO	NUMBER		NOT NULL,
	CBOARD_NO	NUMBER		NOT NULL,
	CREPLY_PARENT	NUMBER		NULL,
	CREPLY_CONTENT	VARCHAR2(2000)		NOT NULL,
	CREPLY_INSERT	DATE	DEFAULT SYSDATE	NOT NULL,
	CREPLY_UPDATE	DATE		NULL,
	CREPLY_DELETE	DATE		NULL,
    FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO),
    FOREIGN KEY (CBOARD_NO) REFERENCES CBOARD(CBOARD_NO),
    FOREIGN KEY (CREPLY_PARENT) REFERENCES CREPLY(CREPLY_NO)
);

DROP SEQUENCE SEQ_RCATTACHMENT;

CREATE SEQUENCE SEQ_RCATTACHMENT NOCYCLE;

CREATE TABLE RCATTACHMENT (
	RCATTACHMENT_NO	NUMBER PRIMARY KEY,
	RCREPLY_NO	NUMBER		NOT NULL,
	RCATTACHMENT_ORIGIN	VARCHAR2(200)		NOT NULL,
	RCATTACHMENT_CHANGE	VARCHAR2(200)		NOT NULL,
	RCATTACHMENT_PATH	VARCHAR2(200)		NOT NULL,
	RCATTACHMENT_INSERT	DATE	DEFAULT SYSDATE	NOT NULL,
	RCATTACHMENT_LEVEL	NUMBER	DEFAULT 0	NOT NULL,
    FOREIGN KEY (RCREPLY_NO) REFERENCES CREPLY(CREPLY_NO)
);

CREATE TABLE RECOMMEND (
	RECOMMEND_MEMBER	NUMBER		NOT NULL,
	CREPLY_NO	NUMBER		NOT NULL,
    FOREIGN KEY (RECOMMEND_MEMBER) REFERENCES MEMBER(MEMBER_NO),
    FOREIGN KEY (CREPLY_NO) REFERENCES CREPLY(CREPLY_NO)
);

CREATE TABLE CRELATION (
	CBOARD_NO	NUMBER		NOT NULL,
	TAGS_NO	NUMBER		NOT NULL,
    FOREIGN KEY (CBOARD_NO) REFERENCES CBOARD(CBOARD_NO),
    FOREIGN KEY (TAGS_NO) REFERENCES TAGS(TAGS_NO)
);

-- 영훈씨
DROP SEQUENCE SEQ_HBOARD;

CREATE SEQUENCE SEQ_HBOARD NOCYCLE;

CREATE TABLE HBOARD (
	HBOARD_NO	NUMBER PRIMARY KEY,
	HBOARD_TITLE	VARCHAR2(400)		NOT NULL,
	HBOARD_CONTENT	VARCHAR2(4000)		NOT NULL,
	HBOARD_INSERT	DATE	DEFAULT SYSDATE	NOT NULL,
	HBOARD_UPDATE	DATE		NULL,
	HBOARD_DELETE	DATE		NULL,
	HBOARD_VIEWS	NUMBER	DEFAULT 0	NOT NULL,
	COMPANY_NO	NUMBER		NOT NULL,
	HBOARD_START	DATE		NOT NULL,
	HBOARD_END	DATE		NULL,
	HBOARD_SALARY	NUMBER	DEFAULT 0	NOT NULL,
	HBOARD_EDUCATION	VARCHAR2(40)		NULL,
	HBOARD_CAREER	VARCHAR2(40)		NULL,
    HBOARD_LOCATION VARCHAR2(400) NOT NULL,
    FOREIGN KEY (COMPANY_NO) REFERENCES COMPANY(COMPANY_NO)
);

COMMENT ON COLUMN HBOARD.HBOARD_INSERT IS '작성된 날짜';

CREATE TABLE HWISHLIST (
	HWISHLIST_MEMBER	NUMBER		NOT NULL,
	HBOARD_NO	NUMBER		NOT NULL,
    FOREIGN KEY (HWISHLIST_MEMBER) REFERENCES MEMBER(MEMBER_NO),
    FOREIGN KEY (HBOARD_NO) REFERENCES HBOARD(HBOARD_NO)
);

DROP SEQUENCE SEQ_HATTACHMENT;

CREATE SEQUENCE SEQ_HATTACHMENT NOCYCLE;

CREATE TABLE HATTACHMENT (
	HATTACHMENT_NO	NUMBER PRIMARY KEY,
	HBOARD_NO	NUMBER		NOT NULL,
	HATTACHMENT_ORIGIN	VARCHAR2(200)		NOT NULL,
	HATTACHMENT_CHANGE	VARCHAR2(200)		NOT NULL,
	HATTACHMENT_PATH	VARCHAR2(200)		NOT NULL,
	HATTACHMENT_INSERT	DATE	DEFAULT SYSDATE	NOT NULL,
	HATTACHMENT_LEVEL	NUMBER	DEFAULT 0	NOT NULL,
    FOREIGN KEY (HBOARD_NO) REFERENCES HBOARD(HBOARD_NO)
);

CREATE TABLE HRELATION (
	HBOARD_NO	NUMBER		NOT NULL,
	TAGS_NO	NUMBER		NOT NULL,
    FOREIGN KEY (HBOARD_NO) REFERENCES HBOARD(HBOARD_NO),
    FOREIGN KEY (TAGS_NO) REFERENCES TAGS(TAGS_NO)
);

DROP SEQUENCE SEQ_CALENDAR;

CREATE SEQUENCE SEQ_CALENDAR NOCYCLE;

CREATE TABLE CALENDAR (
	CALENDAR_NO	NUMBER	PRIMARY KEY,
	PROJECT_NO	NUMBER		NOT NULL,
	CALENDAR_TITLE	VARCHAR2(200)		NOT NULL,
	CALENDAR_CONTENT	VARCHAR2(500)		NULL,
	START_POINT	DATE		NOT NULL,
	END_POINT	DATE		NOT NULL,
    FOREIGN KEY (PROJECT_NO) REFERENCES PROJECT(PROJECT_NO)
);

COMMIT;

DROP SEQUENCE SEQ_RECRUITMENT_STATE;

CREATE SEQUENCE SEQ_RECRUITMENT_STATE NOCYCLE;

CREATE TABLE RECRUITMENT_STATE (
    RECRUITEMNT_STATE_NO   NUMBER      PRIMARY KEY,
	RECRUITMENT_NO		NUMBER		NOT NULL,
	ROLE			VARCHAR2(60)	NOT NULL,
	MAX_PERSONNEL		NUMBER		DEFAULT 1 	NOT NULL,
	FOREIGN KEY (RECRUITMENT_NO) REFERENCES RECRUITMENT (RECRUITMENT_NO)
);

COMMIT;

CREATE TABLE APPLY_PERSONNEL(
    RECRUITEMNT_STATE_NO    NUMBER  NOT NULL,
    MEMBER_NO   NUMBER  NOT NULL,
    FOREIGN KEY (RECRUITEMNT_STATE_NO) REFERENCES RECRUITMENT_STATE (RECRUITEMNT_STATE_NO),
    FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO)
);

COMMIT;

